### PR TITLE
Child now correctly sends new size. AMD/CommonJS/window export support.

### PR DESCRIPTION
**Pull request by acmcelwee**
Previously, `messageParent` was the event handler, but it was consuming the event as the `scrollTop` argument. I've fixed that so there's an intermediate event handler that then calls `messageParent`.

Also, the `resize` and `onresize` events were subscribed to, but that isn't an event that would fire when the content size in the iframe changes. You have to resort to polling for this change, so I've added the polling with a tuneable polling interval.

I've also patched up the CommonJS support and added AMD support. Previously, there was a `module` variable declared in the same scope where the the `module.exports` call was happening.

Finally, the child embed page now has the option to only force a frame resize on content size changes, rather than on content size changes AND the initial load. I see the common use where the initial size is known, but over time, the dynamic content changes require a resize of the container.

### CODE REVIEW

**Comment by mbseid** [comment]
Thanks for this pull request.  Most of it looks great, but I have run into one problem. 

When resizing the window, from small to large, the iframe does not shrink to fit its size.  I believe this is caused by the new docHeight function, but I will do some more investigation soon. It seems like it is getting the max of the window, causing the height to stay the same, unless the document gets bigger. 

We need a way to check and see if the frame shrinks, then respond to those changes. If you have any ideas, please share.

Thanks!

**Comment by acmcelwee** [comment]
I'll look at that scenario when I get a chance.

**Comment by stevies** [comment]
Any update on this?  It would be good if when the page content inside the iframe gets shorter, that the parent page resizes the iframe to match the new shorter height.  Right now, it works one way only - if the page gets taller, then the iframe resizes OK - but not if the child page gets smaller.

**Comment by acmcelwee** [comment]
Completely forgot about this. I'll take a look over the next couple days,
and make an update to accommodate that behavior.

**Comment by stevies** [comment]
Something like this appears to work in latest Chrome, IE and Firefox. 

```
ResponsiveIframe.prototype.allowResponsiveEmbedding = function(opts) {
    var previousHeight, previousBodyOffsetHeight;

    ...
}

function checkHeight() {
        var currentBodyOffsetHeight = document.body.offsetHeight,
            hasShrunk = currentBodyOffsetHeight < previousBodyOffsetHeight,
            currentHeight = getDocHeight();

        if (hasShrunk || !previousBodyOffsetHeight) {
            currentHeight = currentBodyOffsetHeight;
        }

        if (currentHeight !== previousHeight || hasShrunk) {
            previousBodyOffsetHeight = currentBodyOffsetHeight;
            previousHeight = currentHeight;
            messageParent(currentHeight);
        }
    }
```

**Pull request closed without merging**
